### ISSUE TITLE
Incorrect exports from index.js

### ISSUE THREAD

**Issue by arshjat** [jitsi/rnnoise-wasm#10]
the exports 

export createRNNWasmModule from "./dist/rnnoise";
export createRNNWasmModuleSync from "./dist/rnnoise-sync"

are giving error:
Unexpected keyword or identifier

Correct way:

```
diff --git a/node_modules/@jitsi/rnnoise-wasm/index.js b/node_modules/@jitsi/rnnoise-wasm/index.js
index ac03d6c..5706cb7 100644
--- a/node_modules/@jitsi/rnnoise-wasm/index.js
+++ b/node_modules/@jitsi/rnnoise-wasm/index.js
@@ -1,2 +1,4 @@
-export createRNNWasmModule from "./dist/rnnoise";
-export createRNNWasmModuleSync from "./dist/rnnoise-sync"
\ No newline at end of file
+import createRNNWasmModule from "./dist/rnnoise";
+import createRNNWasmModuleSync from "./dist/rnnoise-sync"
+
+export { createRNNWasmModule, createRNNWasmModuleSync }
\ No newline at end of file
```

**Comment by saghul** [comment]
Yoy may need a transpiler, that is valid: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#re-exporting_aggregating

**Comment by arshjat** [comment]
Hi @saghul ,

Thank you for your response and for pointing me to the MDN documentation. While I understand that the syntax you’ve used is valid when paired with an appropriate transpiler configuration, I believe that this approach introduces unnecessary friction for end users of this library. Here’s why:

Open Source Best Practices:
The goal of an open-source library should be to provide a seamless experience for the end user. Requiring users to configure a specific transpiler setup adds an additional barrier to adoption, especially for something as simple as importing and using a module.

Minimal Configuration for Consumers:
Many users (like me) may expect the library to work out of the box with the default configurations of popular build tools (e.g., Webpack, Vite, or Node.js). The syntax currently used in the index.js file is not supported by default in many environments and fails without manual intervention.

Pragmatism over Purity:
While the syntax is valid under certain conditions, the majority of JavaScript projects do not use a transpiler setup that supports this by default. For instance:

Node.js (even in its ES module implementation) does not recognize this syntax.
Many bundlers would require additional Babel or TypeScript configurations, which most developers should not need to do for a library integration.
Practical Alternatives:
A simpler, more universally compatible syntax like the one I’ve proposed (import followed by export) avoids these issues while adhering to modern standards. It also aligns with how the majority of JavaScript libraries handle re-exports today, ensuring a consistent developer experience.

Impact on Developer Perception:
It’s not about whether the current implementation is “valid” or not; it’s about making the library more accessible and robust for everyone. Requiring extra setup can frustrate users, potentially leading them to abandon the library or perceive it as poorly maintained.

My intention here is to help improve this library for the benefit of its users. I would strongly recommend adopting the proposed change to reduce friction and ensure compatibility across environments.

Thanks again for your time and effort in maintaining this project. I’m happy to assist further if needed!

Best regards,
@arshjat

**Comment by saghul** [comment]
It's a simple change, so I wouldn't mind landing a PR if you're up for writing one.
