### ISSUE TITLE
Integration with Debian/Ubuntu packages

### ISSUE THREAD

**Issue by YeaSeb** [jitsi/rnnoise-wasm#3]
I'm not using docker and on the packages from debian repo, after installing, I see rnnoise.wasm on /usr/share/jitsi-meet/libs but can't find the rnnoise-processor js anywhere. I don't hear it enabled either. 
Could it be enabled by hand? Do I need to change the config files or will I need to recompile jitsi-meet to include all necessary libs? 
If it's not usable, why is the rnnoise.wasm file there to begin with?

**Comment by damnms** [comment]
how does that work at all? :D is there somewhere a guide or so? would really like to use jitsi but the background noise is extreme!

**Comment by saghul** [comment]
The rnnoise processor is here: https://github.com/jitsi/jitsi-meet/blob/master/react/features/stream-effects/rnnoise/RnnoiseProcessor.js it gets bundled with the rest of the JS code, so it's part of app.js. The WASM part needs to be separate and it's dynamically loaded.

Note that we are not using rnnoise to suppress noise but rather to detect it. It's used for implementing the "trying to speak?" and "your mic is too noisy" features.

**Comment by damnms** [comment]
thanks for clarification!
